// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetEncCollision struct {
	EncData string `form:"enc_data"`
}

type ResultGetEncCollision struct {
	CollisionResult int64 `json:"collision_result"`
}

type RespGetEncCollision struct {
	Status int                   `json:"status"`
	Msg    string                `json:"msg"`
	Err    string                `json:"err"`
	Result ResultGetEncCollision `json:"result"`
}
