// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetEncCollision struct {
	EncData string `form:"enc_data"`
}

type ResultGetEncCollision struct {
	CollisionResult int64 `json:"collision_result"`
}

type RespGetEncCollision struct {
	Status int                   `json:"status"`
	Msg    string                `json:"msg"`
	Err    string                `json:"err"`
	Result ResultGetEncCollision `json:"result"`
}

type ReqGetEncCollisionBatches struct {
	EncDataBatches []string `form:"enc_data_batches"`
}

type ResultGetEncCollisionBatches struct {
	EncData         string `json:"enc_data"`
	CollisionResult int64  `json:"collision_result"`
}

type RespGetEncCollisionBatches struct {
	Status int                             `json:"status"`
	Msg    string                          `json:"msg"`
	Err    string                          `json:"err"`
	Result []*ResultGetEncCollisionBatches `json:"result"`
}
